export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADED_SUCCESS = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';


export const MODAL_TOGGLE = 'MODAL_TOGGLE';