export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADED_SUCCESS = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';


export const MODAL_TOGGLE = 'MODAL_TOGGLE';

export const GET_ERRORS = 'GET_ERRORS';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const FETCH_NEWSFEED_START = 'FETCH_NEWSFEED';
export const FETCH_NEWSFEED_SUCCESS = 'FETCH_NEWSFEED_SUCCESS';
export const FETCH_NEWSFEED_FAIL = 'FETCH_NEWSFEED_FAIL';
export const LOAD_MORE_NEWSFEED_SUCCESS = 'LOAD_MORE_NEWSFEED_SUCCESS';

export const SAVE_USERS = 'SAVE_USERS';