export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';


export const USER_LOADING_START = 'USER_LOADING_START';
export const USER_LOADING_SUCCESS = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';


export const MODAL_TOGGLE = 'MODAL_TOGGLE';

export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';

export const FETCH_NEWSFEED_START = 'FETCH_NEWSFEED';
export const FETCH_NEWSFEED_SUCCESS = 'FETCH_NEWSFEED_SUCCESS';
export const FETCH_NEWSFEED_FAIL = 'FETCH_NEWSFEED_FAIL';
export const LOAD_MORE_NEWSFEED_START = 'LOAD_MORE_NEWSFEED_START';
export const LOAD_MORE_NEWSFEED_SUCCESS = 'LOAD_MORE_NEWSFEED_SUCCESS';
export const CLEAR_POSTS = 'CLEAR_POSTS';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
export const FETCH_USER_POSTS_START = 'FETCH_USER_POSTS_START';
export const FETCH_USER_POSTS_SUCCESS = 'FETCH_USER_POSTS_SUCCESS';
export const FETCH_USER_POSTS_FAIL = 'FETCH_USER_POSTS_FAIL';
export const LOAD_MORE_USER_POSTS_START = 'LOAD_MORE_USER_POSTS_START'
export const LOAD_MORE_USER_POSTS_SUCCESS = 'LOAD_MORE_USER_POSTS_SUCCESS'


export const SAVE_USERS_SUCCESS = 'SAVE_USERS_SUCCESS';
export const CLEAR_USERS = 'CLEAR_USERS';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
export const CLEAR_PICKED_USER = 'CLEAR_PICKED_USER';